### ISSUE TITLE
请问下UI部分有开源吗

### ISSUE THREAD

**Issue by skyw4code** [Monibuca/plugin-gateway#13]
请问下UI部分有开源吗？需要源码...

**Comment by charlestamz** [comment]
v3 开始 界面没有源码了，我估计是作者太忙，忘了

**Comment by lshsuper** [comment]
v3版本的编译不过。。。D:\Services\goproject\pkg\mod\github.com\!monibuca\plugin-gateway\v3@v3.0.9\main.go:6:2: package embed is not in GOROOT (D:\Services\go\src\embed)

**Comment by bosscheng** [comment]
@skyw4code 页面免费使用，v3的UI源码不开源。

**Comment by bosscheng** [comment]
@charlestamz v3 的UI源码不开源，界面是可以免费使用的。
